[[redirects]]
  from = "/api/*"
  to = "http://olivia.hidencloud.com:24733/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/juego/clickpvponline/*"
  to = "/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: data:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; upgrade-insecure-requests; block-all-mixed-content"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
